#!/bin/sh
name=`echo $PWD | rev | cut -d / -f 1 | rev`
nameSafe=`echo $name | sed 's/-/_/g'`
group=painkillergis
find . ! -path './.git/*' ! -path './build/*' -type f | xargs sed -i "s/ktor-starter/$name/g"
find . ! -path './.git/*' ! -path './build/*' -type f | xargs sed -i "s/painkillergis/$group/g"
find . ! -path './.git/*' ! -path './build/*' -type f | xargs sed -i "s/ktor_starter/$nameSafe/g"
find . -depth -type d -name ktor_starter -execdir mv {} $nameSafe \;
find . -depth -type d -name painkillergis -execdir mv {} $group \;
mv scripts/ktor-starter.service scripts/$name.service
rm eject
git add --all
git commit -m "ejected from ktor-starter"

if [[ `git remote get-url origin` == "git@github.com:painkillergis/ktor-starter.git" ]] ; then
  git remote rm origin
fi

echo if you plan on deploying to yagni, consider changing the port number in "scripts/<your_app>.service" and scripts/deploy.yagni
