#!/bin/sh
./gradlew \
  clean shadowJar docker dockerPush darkDeploy test switchDeployments \
  -DstepperHost=painkiller.arctair.com \
  -DstepperBasePath=stepper \
  -DtargetHost=painkiller.arctair.com \
  -DtargetBasePath=ktor-starter \
  -Dktor_starter_baseUrl=http://painkiller.arctair.com/ktor-starter-dark